
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: milestone_1_query_1
    description: "A starter dbt model"
    columns:
      - name: category
        description: "category of this table"
        tests:
          - not_null
  - name: milestone_1_query_2
    description: "A starter dbt model"
    columns:
      - name: category
        description: "category of this table"
        tests:
          - not_null